### ISSUE TITLE
Support object-based preconditions for representation descriptions

### ISSUE THREAD

**Issue by AresEkb** [eclipse-sirius/sirius-components#1014]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : 2021.12.12
* [x] **I have specified my environment** : Linux

### Steps to reproduce

1. Add precondition expression containing `self` variable for a representation specification in odesign-file
2. Try to create the representation

### Expected behavior

The representation kind is available in the new representation dialog and successfully created.

### Actual behavior

The representation kind is not available in the new representation dialog. The following exception is raised: "An error has occurred with the expression 'aql:self.getModelKindMnemonic() = 'EventDrivenProcessChain'': Couldn't find the 'self' variable"

### Details

Class `org.eclipse.sirius.web.emf.handlers.EditingContextRepresentationDescriptionsEventHandler` contains the following code:
```
VariableManager variableManager = new VariableManager();
variableManager.put(IRepresentationDescription.CLASS, optionalClazz.get());
Predicate<VariableManager> canCreatePredicate = description.getCanCreatePredicate();
boolean canCreate = canCreatePredicate.test(variableManager);
```
Only `class` variable is added.

I guess the problem is that `org.eclipse.sirius.web.spring.collaborative.dto.EditingContextRepresentationDescriptionsInput` has only a `kind` parameter. The selected object is not even send in a GraphQL query.

However property forms support preconditions with `self` variable. `org.eclipse.sirius.web.spring.collaborative.forms.dto.PropertiesEventInput` has `objectId` parameter instead of `kind`.

Maybe behaviour for representations should be aligned with the behaviour for forms? Both of them should support `self` in preconditions?

**Comment by pcdavid** [comment]
Fixed via #1288
