### ISSUE TITLE
Scalability issue with deep/complex diagram descriptions

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#1036]
Since https://github.com/eclipse-sirius/sirius-components/pull/960/commits/e3a37e883cb7ab5c3712c190926cd06e5e9f54f9 we send (a subset of) the `DiagramDescription` to the frontend so that it can make more informed decisions, in particular [whether or not  to provide a 'Delete from diagram' tool for unsuynchronized nodes](https://github.com/eclipse-sirius/sirius-components/pull/960/commits/1e2b89770d2d399f114e78a568f28d537c513efb#diff-6e6411fb31a0ef4291f8485a118f217275ccf5865830f8053dd649c5bc84362dR66).

This works fine for relatively simple diagram descriptions, but does not scale well for more complex ones.
For example for a diagram with, say 20 different kinds of nodes which can all contain each other with no depth limit, [the GraphQL query](https://github.com/eclipse-sirius/sirius-components/pull/960/commits/e3a37e883cb7ab5c3712c190926cd06e5e9f54f9#diff-3c6a2180a0b55ca6fdeaec04c280c9df0239a1d7ffd15ed7523019c9b7b69fd8R363) to retrieve the diagram description's structure, even if it is limited to a depth of 4, will return at least 20×20×20×20 = 160000 elements! With 30 different kinds of node, 30^4 = 810000, etc.

Note that the changes planned for https://github.com/eclipse-sirius/sirius-components/issues/779 may indirectly solve this by replacing this whole static query with on-demand queries about the tools and properties of a node only when it is selected, which will not be recursive.

**Comment by sbegaudeau** [comment]
The frontend does not retrieve the diagram description anymore.
