### ISSUE TITLE
The domain class is not taken into account for DomainBasedEdges

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#105]
It seems https://github.com/eclipse-sirius/sirius-components/blob/3ce98268d673ce5abfa1771738e3a2feffbb8de5/backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java#L213 does not take into account domain class for domain-based Edges

**Comment by pcdavid** [comment]
See https://github.com/eclipse-sirius/sirius-components/pull/106 (don't know why GitHub did not create the link; I guess the reference in the title is not enough and only something like "Fixes #105" in the body is considered...)
