### ISSUE TITLE
Node creation event outside of container bounds forces its resize

### ISSUE THREAD

**Issue by RaphaelPageObeo** [eclipse-sirius/sirius-components#1051]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- my computer: Windows

### Screenshots

![before](https://user-images.githubusercontent.com/61457677/153230047-a4f1f723-787f-4916-9930-fa207661a969.png)

### Steps to reproduce

- I have two root nodes, A { size: 200x300, position: 10;10 } (in blue) and B { size: 200x300, position: 500;500} (in orange)
- I click on (100;100) (inside A, red dot) and send a creation event
- The editing context actually creates the new node in B

### Expected behavior

- A { size: 200x300, position: 10;10 } 
- B { size: 200x300, position: 500;500 } 
- Child { size: 150x70, position: 510;510 } 

A is not resized. B is not resized either, since it is big enough to contain the new node. The new node is created in B, since it is a son of B.

![Fixed](https://user-images.githubusercontent.com/61457677/153231412-d5361528-e2d9-4c45-8249-b74c9e63c41c.png)

### Actual behavior

- A { size: 200x300, position: 10;10  } 
- B { size: 600x700, position: 231;231 } 
- Child { size: 150x70, position: 231;231 } 

A is not resized. The new node is created in B...but not at the right coordinates, which forces B to be resized

![Actual](https://user-images.githubusercontent.com/61457677/153230098-91b5b86a-fef0-42cc-8fdf-7eccc50f4b35.png)

**Comment by gcoutable** [comment]
I don't understand why the click inside A creates a child in B.
Does the child already exist in the model and it is a child of B?

**Comment by sbegaudeau** [comment]
Yes, it's to simulate an operation triggered by a tool on A which creates a child in B. I think I won't surprise you by saying that it was my idea :p
