### ISSUE TITLE
Handle icon property from OperationAction in the compatibility layer

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#1075]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Unlike many others concept in the _odesign_, _OperationAction_ handles custom **icon** through the **icon** property instead of the **iconPath** property.
_ToolImageProvider_ only handles **iconPath** property for now.
An improvement could be to also handle **icon** property in _ToolImageProvider_.

**Comment by sbegaudeau** [comment]
Closing this since it has been merged
