### ISSUE TITLE
Add support for form descriptions in the View DSL

### ISSUE THREAD

**Issue by florianbarbin** [eclipse-sirius/sirius-components#1149]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

It will be possible to create a new Form Descriptions in the View DSL. It will be possible to define widgets (Textfields, checkbox, radio button, labels, buttons etc)

### Cuttings backs

...

### Potential side effects

...

### Describe alternatives you've considered

...

**Comment by sbegaudeau** [comment]
Could have been closed a long time ago since the relevant work has been merged.
