### ISSUE TITLE
Force ELK to use the label width in nodeContainer layout

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-components#117]
When ELK computes a nodeContainer width, it will ignore the nodeContainer label width when a node child is present.

Example:
![cap 103](https://user-images.githubusercontent.com/1506357/100337288-7a399400-2fd7-11eb-8349-e0551c335c1c.png)

I propose to add a virtual ElkNode that will force ELK to consider this minimum width as a constraint.

**Impacts: layout/refresh**

**Tests: Junit/Cypress**

**Comment by lredor** [comment]
It seems strange. The property should be considered. This is the case in this [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE5okCMaA3kWk1eTgMowBeOAdAMYQSAZzhRgMEnCHoARAG0AcgHkAIgFEA+gBkAggCE1WtgF0ZjZmQpbgAIxwghPAA6Y+OJDkmy5ACQ0BhNQUAFTUAJQAaNAA1DWClAAUogEkFNmT1UyIASEw7EDQtalkdADc8LBBBMBJgDwBaMoqqkhq6nBl6HNzsCABXODQ5buyhLhx0ACYABmmo6gB2buMcgF9zJktKEkmu5n2MXoG5Me4pubQZlf311aA).

**Comment by lredor** [comment]
Vigilant point with the propose workaround:
* The node will no longer be centered with the property NodeLabelPlacement.insideTopCenter(). You have to do it manually.
* You need to add a specific margin to avoid default space around node.

**Comment by sbegaudeau** [comment]
Closing this issue since we will instead wrap the label
