### ISSUE TITLE
Add an optional icon for widgets

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#1215]
For https://github.com/eclipse-sirius/sirius-components/issues/1140 we want to display a toggle button for each widget inside a `Group` to allow the user to hide/reveal them individually.
The planned UI needs a label and an icon for these toggle buttons.

For the labels, see https://github.com/eclipse-sirius/sirius-components/issues/1214.

Currently, none of the widgets have an associated icon. We do not want to overcrowd the default forms UI (details page, form representations) with an icon per widget, but *in the context of the toggle buttons for #1140*, we want to be able to display such an icon.

This change will add a new `iconURL` on all widgets, but will keep it optional.
For now it will only be used (if defined) in the toggle buttons group for #1140.

**Comment by sbegaudeau** [comment]
Do we want such an iconURL to be optional and configurable? Couldn't we have some frontend hardcoded icon representing the type of widget (textfield, checkbox, tree, etc)?

**Comment by pcdavid** [comment]
I wanted to minimize the impact, but sure we could make it mandatory, even if we do not display the icons in the default _Details_ view.
I guess the form description editor itself has/should have icons for each type of widget, and the default provider for a given widget instance would use the one corresponding to its type.

**Comment by pcdavid** [comment]
For the "configurable" part of the question: yes we want to be able to provide different icons for different instances of the same type of widgets. Case in point: the "Related Elements"  view (https://github.com/eclipse-sirius/sirius-components/issues/1141) will display (by default) 3 instances of the _Tree_ widget, and each should have a different icon.
