### ISSUE TITLE
Handle conditional styling for ViewDSL widgets

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#1236]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Handle conditional styling for the following ViewDSL widgets : textfield, textarea, radio, checkbox, select, multiselect.

### Cuttings backs

...

### Potential side effects

...

### Describe alternatives you've considered

...

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse-sirius/sirius-components/pull/1241
