### ISSUE TITLE
Download Project fails when model contains a Form Description Editor

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#1260]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- my computer: MacOS

### Screenshots

...

### Steps to reproduce

1. Create a project
2. Create a View
3. Create a Form Description
4. Create a Form Description Editor on the Form Description
5. Download the project

### Expected behavior

The download succeeds

### Actual behavior

The download fails and an error page is displayed

**Comment by gcoutable** [comment]
Close this issue because https://github.com/eclipse-sirius/sirius-components/pull/1261 has been merged
