### ISSUE TITLE
Support of unsynchronized mode

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-components#127]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
Provide a way to unsynchronized a graphical element and it semanticCandidate expression.

An unsynchronized graphical element:
- must be create intentionally with a tool
- can be deleted with a delete tool -> the standard behavior will be to delete the unsynchronized graphical element (the semantic element behind will not be deleted)
- will disappear if it related semantic element does not exist anymore (Refresh behavior)

### Cuttings backs
- Handle only graphical nodes (Edge still 100% synchronized)
- Handle only programmatic contributions (This implementation does not handle yet an unsynchronized node that come from an odesign)

### Potential side effects
- Diagram refresh
- Create node tool
- Delete tool

### Describe alternatives you've considered
We have study an incremental refresh strategy to implement this behavior based on the [React approach](https://reactjs.org/docs/reconciliation.html).

The current state of this experimentation:
We don't need an incremental refresh to implement an unsynchronized mode.
We can give the previous unsynchronized element thanks to the variableManager without implement a "React reconciliation" pattern. 
The render method will clone the previous unsynchronized element and re-render it props (according that the semantic element behind isn't deleted).

This "React reconciliation" pattern could be study for a performance issue but it's not this subject here.

**Comment by sbegaudeau** [comment]
We can close this issue since it has been merged in master. Additional improvements will be made with dedicated issues.
