### ISSUE TITLE
Let users switch form description editors properly

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#1282]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- my computer: macOS

### Screenshots

...

### Expected behavior

The switch between opened formdescriptioneditors runs without any problems

### Actual behavior

As it is already done for diagrams and forms, the switch between opened formdescriptioneditors should be done properly.

**Comment by pcdavid** [comment]
Even without the PR, switching between different FormDescriptionEditors work fine for me.
Can you give the specific scenario where you detected an issue, and what was the problem precisely?

**Comment by sbegaudeau** [comment]
Closing this issue since this doesn't seems necessary.
