### ISSUE TITLE
Details section title not visible

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#1298]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : 99
- latest
- other: please specify
* [x] **I have specified my environment** : 
- my computer: Linux

### Screenshots

![image](https://user-images.githubusercontent.com/1185863/177958633-40d65d17-bb7e-4fe2-92fc-9ff96d1c1180.png)

### Steps to reproduce

Open a UML model select an element in the model explorer to show the details view.

### Expected behavior

The size of title's section should not change its size, the size should be fixed.

### Actual behavior
The title is not visible, because the size of the title section is to short.

**Comment by sbegaudeau** [comment]
Fixed on master
