### ISSUE TITLE
Display mutation/query errors in DiagramWebSocketContainer

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-components#130]
* [ ] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Display errors thanks to the Banner component.
Mutation and queries errors in DiagramWebSocketContainer must be clearly displayed.

### Cuttings backs

None

### Potential side effects

Front-end diagram

### Describe alternatives you've considered

None

**Comment by sbegaudeau** [comment]
Closing this issue since it has been done by Florian
