### ISSUE TITLE
The default tool of a tool section is not updated as it should

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-components#1305]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
Windows 10

### Screenshots

https://user-images.githubusercontent.com/7371042/180476779-9a1da4c6-faf8-4744-9632-f7b93108e4ef.mp4

### Steps to reproduce

1. Create a topography diagram
2. Click on `CaptureSubSystem` and expand the tool section, the default tool should be a _Fan_
3. Create a processor using the processor creation tool
4. Click again on `CaptureSubSystem`

### Expected behavior

The default tool should be a _Processor_

### Actual behavior

The default tool is still a _Fan_

**Comment by pcdavid** [comment]
This had already been broken and fixed earlier: https://github.com/eclipse-sirius/sirius-components/issues/419
