### ISSUE TITLE
The convertedNodes variable is not exposed consistently in View-based diagrams

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#1329]
`ViewDiagramDescriptionConverter` exposes the `convertedNodes` variable in the context of node creation tools, but not in others (in particular the drop handler) where it could be useful.

**Comment by sbegaudeau** [comment]
From a quick look at the code, it seems that this variable is exposed only once and never used anywhere in our code (it can be used in a View instance but I haven't seen one using this). What kind of use cases do you have in mind for this variable?

**Comment by pcdavid** [comment]
It's currently needed for some studios which use Java services.
Inside the Java service you may need to reference instances of `org.eclipse.sirius.components.diagrams.description.NodeDescription` (for example to build a `ViewCreationRequest`).
Inside that service, if you need to locate "the `description.NodeDescription` which corresponds to the `view.NodeDescription` named 'MyDomainClass_Description'", the easiest way at the moment is to find it in this map with something like:

```java
convertedNodes.entrySet().stream()
  .filter(entry -> entry.getKey().getName().equals("MyDomainClass_Description"))
  .map(Map.Entry::getValue)
  .findFirst();
```

There might be other ways to do this without the map, searching inside the converted `DiagramDescrition` and relying on how `ViewDiagramDescriptionConverter.idProvider` currently works, but its even more convoluted and seems brittle.

Ideally, https://github.com/eclipse-sirius/sirius-components/issues/1328 would provide injectable APIs that hide all this complexity from the studio makers and render this variable useless, but in the meantime this variables enables these scenarios.
