### ISSUE TITLE
Add a diagram dirty state

### ISSUE THREAD

**Issue by hmarchadour** [eclipse-sirius/sirius-components#135]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

There is a **_time laps_** between an invoke mutation and the related refresh.
This **_time laps_** involves some strange UX behaviors that we can avoid with a dirty state flag.

Use case:
* T0: A mutation (Label edit/invoke delete tool/invoke node or edge tool) is triggering. There is two ways:
* * T1: the mutation succeed
* * *  T2:  a diagram refresh happens
* * T1': the mutation failed

During these **_time laps_** (T0/T2 or T0/T1'), the diagram is in a dirty state.
We should avoid to propose the contextual palette when the user select a diagram element (especially after an invoke tool)

This proposition is based on a premise: **a mutation in success will always update something and throw a diagram refresh**
This proposition may be invalid if this premise is (or becomes) invalid.

### Cuttings backs

None

### Potential side effects

- Contextual palette

### Describe alternatives you've considered

We could involve the dirty state only between (T1/T2)

**Comment by pcdavid** [comment]
I'm not sure "dirty" is the best name for the intermediate state. I don't have a better name (maybe "busy"? not fond of it but I can't find a better alternative at the moment). The usual meaning of "dirty" is more "contains changes which have not yet been saved on permanent storage", which is not the case here.

Side note: it's time *lapse* not *laps*. Laps exists but is somehting else.

**Comment by sbegaudeau** [comment]
I am not sure where this premise `a mutation in success will always update something and throw a diagram refresh's coming from` but it does not exist anywhere in the architecture.

A mutation triggers something to be performed on the project. If the mutation is successful, something may occur which may trigger a refresh.
