### ISSUE TITLE
Upgrade to Spring Boot 2.4.0

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#145]
Some of our projects are using Spring 2.3.4.RELEASE, others are using 2.3.2.RELEASE, all of them will now switch to 2.3.4 (no more RELEASE suffix by the way).

See https://github.com/spring-projects/spring-boot/releases/tag/v2.4.0

**Comment by pcdavid** [comment]
> Some of our projects are using Spring 2.3.4.RELEASE, others are using 2.3.2.RELEASE, all of them will now switch to 2.3.4 (no more RELEASE suffix by the way).

2.4.0, not 2.3.4. But the commit message is fine.

**Comment by sbegaudeau** [comment]
Merged
