### ISSUE TITLE
MutationUpdateWidgetFocusDataFetcher incorrectly returns an error payload to the frontend

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#161]
## Steps to reproduce

1. Open a project and select a semantic element with several properties in the explorer.
2. Open the browser's dev tools on the _Network_ tab.
3. Click on one of the widgets in the properties view.
4. In the _Network_ tab find the `graphql` request which sent the `operationName: "updateWidgetFocus"`
5. The _Response_ for this request is always:

```json
{
  "data": {
    "updateWidgetFocus": {
      "__typename": "ErrorPayload",
      "message": "An unexpected error has occurred, please contact the server administrator"
    }
  }
}
```

## Analysis

When receiving a `UpdateWidgetFocusInput`, `MutationUpdateWidgetFocusDataFetcher` dispatches the event to `IProjectEventProcessorRegistry`. It ends up being treated by `FormEventProcessor.handle(IRepresentationInput, Context)`, which delegates to the supplied `IWidgetSubscriptionManager`, but the subscription updates are sent asynchrnously, and `FormEventProcessor.handle` does not return any value in this case. The default `Optional.empty()` is interpreted by `MutationUpdateWidgetFocusDataFetcher` as an error, so it returns an unexpected error payload.

**Comment by sbegaudeau** [comment]
We are indeed missing an `UpdateWidgetFocusSuccessPayload`
