### ISSUE TITLE
Generalize the use of Apollo Client

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#170]
In #113 we moved to Apollo Client instead of our custom hooks for the diagram part. This is about generalizing this to all the rest of the code base, and completely remove our custom hooks in the end.

**Comment by pcdavid** [comment]
Reopining, as there are several places left to migrate (forms, explorer, upload endpoint), and a few issues to fix (relative to auth integration and caching notably).

**Comment by sbegaudeau** [comment]
I think that we can close that one. A couple of additional improvements can be made (file upload for example) but we will see this later.
