### ISSUE TITLE
Improve the consistency and usages of useProject()

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#178]
The hook `useProject()` was created in order to retrieve in a similar fashion some information regarding the current project for top level components of a a specific set of views. From there, it has been overused without fully understanding the consequences of its use. It should probably have been deleted at this point.

After that it has been provided an additional capability with a dedicated subscription which makes it a provider of both synchronized data and unsynchronized data. While this new capability may give it a reason to stay around, it creates even more issues with the various places where it has been used without understanding its role.

**Comment by pcdavid** [comment]
The `useProject()` hook does not exist anymore.
