### ISSUE TITLE
Image in the resources folder is not shown on the web 

### ISSUE THREAD

**Issue by 4MIR2000** [eclipse-sirius/sirius-components#1804]
Hi everyone, 
I have specified a workspace image in the odesign. However it is not shown on the web. I also dont receive any error messages.
![Screenshot from 2022-06-15 09-12-51](https://user-images.githubusercontent.com/59100935/173766678-63439007-f17b-4f1b-bf36-70e5863311b1.png)
![Screenshot from 2022-06-15 09-12-32](https://user-images.githubusercontent.com/59100935/173766698-9bcc25a8-f235-4248-8f4b-036d9ddeecb2.png)

**Comment by pcdavid** [comment]
> I added the "/resources/images" to the list, but it does not change anything
...
>  When I change the workspace-image path manually to /packagename.design/images it works

So it should work if you register "/images" instead of "/resources/images"?
