### ISSUE TITLE
Icons of Elements not visible when launching app with eclipse

### ISSUE THREAD

**Issue by 4MIR2000** [eclipse-sirius/sirius-components#1808]
Hi everyone, 
I have currently the problem that the icons for the elements and images of newly added elements in odesign are not shown on the webpage, when I launch the app through eclipse. However when I run the jar through the terminal the images are loaded normally. I am using eclipse 2022.03 on Ubuntu 20.04.2
Maybe it has something todo with the caching of eclipse, but since im new to sirius I have no idea and would be thankful if you could help me. 
![3](https://user-images.githubusercontent.com/59100935/172791569-87eaa972-d0bb-43a0-a4d6-b44dfa14701c.png)
![2](https://user-images.githubusercontent.com/59100935/172791575-e4f7b063-9076-41c4-a335-521d31197346.png)
![1](https://user-images.githubusercontent.com/59100935/172791578-9f935781-b621-40af-b2f7-9049999bc538.png)

**Comment by pcdavid** [comment]
Not sure which version of Sirius Web you were using at the time, but I think https://github.com/eclipse-sirius/sirius-components/pull/1125 may have fixed the issue. Feel free to reopen if that is not the case, but note that this is a low priority issue as everything works fine in "deployed" mode.
