### ISSUE TITLE
Shapes for NodeStyle 

### ISSUE THREAD

**Issue by sezginaytac** [eclipse-sirius/sirius-components#1811]
Hi :)  I want to use some shapes for NodeStyle (e.g. Actor in your youtube demos). But the Spape select box displays "None". Probably, I should provide shape resources (svg, png, etc) in somewhere. How can I provide shapes to the sirius web example app built myself? Many thanks in advance for your consideration...

**Comment by pcdavid** [comment]
Note that it is now possible for users to upload custom images, since https://github.com/eclipse-sirius/sirius-components/issues/1386 (available in [v2023.1.0](https://github.com/eclipse-sirius/sirius-components/blob/master/CHANGELOG.adoc#v202310)).
