### ISSUE TITLE
Remove deprecated references to username

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-components#1813]
Hey!

When trying to enable authentication in Sirius Web I noticed the SQL queries used by the `IProjectRepository` do not restrict access to projects based on the `username`

https://github.com/eclipse-sirius/sirius-web/blob/4b91a66492ea1302c222a24c069389a4a207aede/backend/sirius-web-persistence/src/main/resources/db/sirius-web-named-queries.properties#L1-L4

even though it is provided as a parameter

https://github.com/eclipse-sirius/sirius-web/blob/4b91a66492ea1302c222a24c069389a4a207aede/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IProjectRepository.java#L38-L52

I understand Sirius Web is using a single hardcoded `system` user at the moment, so the username does not matter. On the other hand, there seems to be no harm in verifying the username in the queries, because the `system` account is still created, so all queries should return the same results regardless of whether they check the username or not.

Having the username be verified in those SQL queries by default would mean there are fewer changes needed to enable authentication for anyone wanting to develop their own modeler based on Sirius Web.

Just FYI, I added it myself in my work in https://github.com/Gelio/CAL-web/pull/111/commits/fad18f5e6bc5a3b463a29c0ea8498ca83f573eb6 (note that I did not modify all the queries, partly due to https://github.com/eclipse-sirius/sirius-components/issues/846#issuecomment-983440899), but IMO it's worth adding to the upstream repository.

**Comment by pcdavid** [comment]
I believe this has been fixed by https://github.com/eclipse-sirius/sirius-components/issues/1643.
