### ISSUE TITLE
Create a "New Modeler" page

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#219]
This is part of the overall feature to support modeler definition directly inside Sirius Web.

* A new entry named "New modeler" will be added in the project's context menu.
* It will only be visible/enabled for user with _ADMIN_ rights on the project.
* When triggered, the menu will open a new page with a simple form, similar to the current "New project" page, to enter the name of the new modeler and submit.
* When submitted, the new page will send a mutation request to the backend to create the modeler, receive the corresponding editing context, and redirect to the project edition page setup on this new editing contex.

The whole infrastructure to actually create modelers and the corresponding editing context will come later in separate tickets.
The first iteration here will focus on creating the UI and a first version of the mutation needed, with a dummy implementation in the backend.

**Comment by pcdavid** [comment]
New menu entry:

![Capture d’écran de 2021-01-05 09-06-01](https://user-images.githubusercontent.com/10608/103621288-4423f400-4f35-11eb-9410-a1d0971e9fc8.png)

New page:

![Capture-2021-01-05_09-06-29](https://user-images.githubusercontent.com/10608/103621332-556d0080-4f35-11eb-8b40-8bea0378de9a.png)

**Comment by sbegaudeau** [comment]
Merged in master
