### ISSUE TITLE
Create a new page to manage modelers

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#220]
This is part of the overall feature to support modeler definition directly inside Sirius Web.

* A new entry named "Modelers" will be added in the project's context menu.
* It will only be visible/enabled for user with ADMIN rights on the project.
* When triggered, the menu will open a new page with a list of the modelers associated to the project.
* Each modeler has a Name and a Status (_Draft_ or _Published_).
* Each modeler has a context menu with 3 entries:
  * _Rename_
  * _Publish_ (only enabled if the modeler is currently a _Draft_)
  * _Delete_

The whole infrastructure to actually create modelers and the corresponding editing context will come later in separate tickets.
The first iteration here will focus on creating the UI and a first version of the GraphQL Schema (types, queries, mutations needed), with a dummy implementation in the backend.

The menu entry:

![Capture d’écran de 2021-01-05 09-06-01](https://user-images.githubusercontent.com/10608/103622088-7c780200-4f36-11eb-9e21-9070236ed496.png)

The new page:

![Capture-2021-01-05_09-15-36](https://user-images.githubusercontent.com/10608/103622172-97e30d00-4f36-11eb-8257-f567c0da5d0a.png)

**Comment by sbegaudeau** [comment]
Merged in master
