### ISSUE TITLE
Add support for incremental layout

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#232]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

1. deactivate the auto layout at refresh (leave it at creation)
2. make sure to keep the node positions
3. make sure to keep the edge positions
4. ensure that the creation of elements via the model explorer is visible on the diagram
5. make sure that the creation of an edge via the model explorer is visible on the diagram (not sure that we can, do a test action at worst)
6. implementation of an option to activate this mode

**Comment by sbegaudeau** [comment]
Merged in master
