### ISSUE TITLE
 Improve positions and sizes of added / moved elements

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#233]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
After deactivating the layout (#232), we should re-work the positions and sizes of added / moved elements.

- [ ] [Initialize the container size](https://github.com/eclipse-sirius/sirius-components/issues/285)
- [ ] [Move contained element](https://github.com/eclipse-sirius/sirius-components/issues/288)
- [ ] [Resize elements](https://github.com/eclipse-sirius/sirius-components/issues/289)

**Comment by sbegaudeau** [comment]
Duplicate of another issue
