### ISSUE TITLE
Improve the layout around added / moved elements

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#234]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
After deactivating the layout (#232), we should improve the layout around added / moved elements.

- [ ] [Improve the anchor position](https://github.com/eclipse-sirius/sirius-components/issues/286)
- [ ] [Reposition automatically the elements](https://github.com/eclipse-sirius/sirius-components/issues/287)

**Comment by sbegaudeau** [comment]
Duplicate of another issue
