### ISSUE TITLE
Add the ability to move nodes in the diagram

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#238]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
Move elements :
- evaluate Sprotty update
- activate movement in sprotty
- work on feedback when moving elements
- ensure that the movement is transmitted to the server

**Comment by florianbarbin** [comment]
Work in progress on branch https://github.com/wpiers/sirius-components/tree/wpi/enh/moveElement
