### ISSUE TITLE
The explorer definition depends on EMF

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#264]
Currently then only implementation of `IExplorerDescriptionProvider` we have is `org.eclipse.sirius.web.emf.compatibility.explorer.ExplorerDescriptionProvider`, which depends on EMF.

It should be extracted and work on any kind of models/documents and objects inside of them.

This will require moving some APIs like `get(Root)Elements()`, `hasChildren()` and `getChildren()` into more generic APIs like `IEditingContext` and `IObjectService`.

**Comment by sbegaudeau** [comment]
This implementation does not exist anymore in Sirius Components
