### ISSUE TITLE
AQL and Spring Boot use different versions of ANTLR

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#265]
When using the sample application, I get the following message on the console (the first time an AQL expression is evaluated I suppose):

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8
```

We are currently using AQL 7.0.0, which has been built using ANTLR 4.7.2, but the version we get in the classpath (since Spring Boot 2.4.1?) seems to be ANTLR 4.8.

**Comment by sbegaudeau** [comment]
We should switch to the same version as the latest release of hibernate
