### ISSUE TITLE
Properties view does not take custom EDataType in consideration

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#276]
The various `DescriptionProviders` in `org.eclipse.sirius.web.emf.compatibility.properties` have predicates which are too strong. For example `EStringIfDescriptionProvider` will only match `EAttributes` which are exactly typed `EString`, but ignore the ones which use a custom `EDataType` which maps (like `EString`) onto `java.lang.String`.

As an example, trying to display properties views on a Sirius Desktop VSM does not show all the intepreted expressions, as those are typed with the `InterpretedExpression [java.lang.String]` data type defined in `viewpoint.ecore`.

The same is true for booleans (the test `eAttribute.getEType().equals(EcorePackage.Literals.EBOOLEAN)` is too strict), and in `NumberIfDescriptionProvider`, where `eAttribute.getEType().equals(this.eDataType)` should also consider the case where `eAttribute.getEType().getInstanceClassName().equals(this.eDataType.getInstanceClassName())`.

**Comment by sbegaudeau** [comment]
Merged in master
