### ISSUE TITLE
Some tests are ignored (and broken) since the move to Spring Boot 2.4.0

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#277]
Since we moved to Spring Boot 2.4.0 (in 3de3c795396e92db1c65596bb5a5d16a0deec41c), the tests in some of our Maven modules are no longer detected and run, and some of those have now KO without anyone noticing.

This is caused by Spring Boot 2.4.0 removing support for JUnit 4 runners by default, see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test. We did not add the "vintage" runner dependency, so JUnit 5 does not see our JUnit 4 style tests.

The projects impacted are:
```
sirius-web-emf/pom.xml
sirius-web-persistence/pom.xml
sirius-web-spring-graphql/pom.xml
sirius-web-spring/pom.xml
sirius-web-test-diagrams-only-application/pom.xml
sirius-web-test-sample-application/pom.xml
```

Once the dependency is added back, the tests are correctly found and executed, but there are test failures that we did not notice in `sirius-web-emf` and `sirius-web-persistence`.

**Comment by sbegaudeau** [comment]
Merged in master
