### ISSUE TITLE
Improve the anchor position

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#286]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
The edges anchors are positionned on the element's center (for the source and the target).

The anchor must be positionned on the element's borders.
The border and the position must be chosen smartly according to the direction and the already connected edges on a same border.

**Comment by mt-empty** [comment]
This is working as of `0.2.18`
![image](https://user-images.githubusercontent.com/59728838/112471790-6ef94800-8dc0-11eb-8725-c9fc916ebc9d.png)
