### ISSUE TITLE
Documentation of sirius-web-emf

### ISSUE THREAD

**Issue by rbelafia** [eclipse-sirius/sirius-components#345]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : latest
* [x] **I have specified my environment** : All

### Screenshots

![capture_sirius_web_emf_documentation](https://user-images.githubusercontent.com/50581931/108877331-68c84e00-75ff-11eb-8606-720f9e9bea91.png)

### Steps to reproduce

Check [`sirius-web-emf` documentation](https://github.com/eclipse-sirius/sirius-components/blob/master/backend/sirius-web-emf/README.adoc).

### Expected behavior

Documentation for [`sirius-web-emf`](https://github.com/eclipse-sirius/sirius-components/tree/master/backend/sirius-web-emf) component.

### Actual behavior

Documentation for [`sirius-web-annotations`](https://github.com/eclipse-sirius/sirius-components/tree/master/backend/sirius-web-annotations) component.

**Comment by sbegaudeau** [comment]
This wrong copy / paste has been fixed quite some time ago
