### ISSUE TITLE
Acceleo 3 queries don't get evaluated

### ISSUE THREAD

**Issue by berezovskyi** [eclipse-sirius/sirius-components#443]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : 
- latest (0.2.18 as of 2021-04-16)
* [x] **I have specified my environment** : 
- macOS Catalina latest
- IntelliJ
- AdoptOpenJDK 11
- Maven 3.8.1
- Tycho 2.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/64734/115084875-c2673d80-9f09-11eb-8a11-780cefcb0ed2.png)

### Steps to reproduce

- Initialise sample sirius-web app to use an odesign file that contains Acceleo 3/MTL expressions like `['vocab' + container.vocabularies->size() /]` ([source](https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign#L1507)).
- Create a new model
- Create a new representation
- Add an item to the diagram

### Expected behavior

- An item is created and added to the diagram with default values evaluated to some values.

### Actual behavior

- An item is created and added to the diagram with Acceleo 3 expressions as default values verbatim. 

---

I see that in https://github.com/eclipse-sirius/sirius-components/blob/master/backend/sirius-web-interpreter/src/main/java/org/eclipse/sirius/web/interpreter/ExpressionConverter.java there is handling code for all kinds of expressions except Acceleo 3. Do we need to perform extra configuration to get them working or does Sirius Web not support Acceleo 3 at all?

_cc @jadelkhoury_

**Comment by pcdavid** [comment]
Hi, this is a known limitation.
At the moment we have no plan to support Acceleo 3 expressions.
Of course that can change in the future, but this is not on our roadmap at the moment as in general [AQL](https://www.eclipse.org/acceleo/documentation/aql.html) is better suited for this kind of usage.

**Comment by berezovskyi** [comment]
Thank you, Pierre-Charles! I understand that Acceleo 3 is not on the roadmap and you can close the issue if you wish.

**Comment by pcdavid** [comment]
Thanks for the feedback, closing. If we ever work on this we'll try to reuse this issue so that you get notified.
