### ISSUE TITLE
Invalid position for newly created elements

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#450]
On the "Robot Flow" example, creating a new _Fan_ inside a container no longer places the new element at the correct location. See the two fans at the bottom-right of the screenshot:

![2021-04-22_14-48](https://user-images.githubusercontent.com/10608/115716806-dd0e3c00-a379-11eb-974b-eba331e40303.png)

Note that before the creation of the first Fan, the _Central Unit_ container was much smaller; it automatically expanded when I created the first one.

**Comment by pcdavid** [comment]
See https://youtu.be/XLLn8s0bsBQ

**Comment by sbegaudeau** [comment]
https://user-images.githubusercontent.com/422587/115718813-c832a800-a37b-11eb-9d4d-f67f87cd4d0d.mp4

**Comment by pcdavid** [comment]
Another probably related case, this time creating a node directly on the diagram's background at a location with no risk of overlap:

https://user-images.githubusercontent.com/10608/115846405-274af800-a422-11eb-9f1a-dd12d87a7975.mp4

**Comment by pcdavid** [comment]
Speeking of overlaps...

https://user-images.githubusercontent.com/10608/115846714-77c25580-a422-11eb-98d9-2ffee75e4bcf.mp4
