### ISSUE TITLE
Renaming a diagram does not update the Navigation bar where the project name should be updated

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-components#467]
### Steps to reproduce

1. Create a new project
2. From the _Project Editor View_, use the global menu to rename the project

### Expected behavior

The Navigation bar should be updated.

### Actual behavior

The Navigation bar has the previous name

**Comment by pcdavid** [comment]
I think this corresponds to https://github.com/eclipse-sirius/sirius-components/issues/377

**Comment by sbegaudeau** [comment]
Duplicate of another issue
