### ISSUE TITLE
AQL expressions that include calls relating to the referenced metamodels fail to execute

### ISSUE THREAD

**Issue by berezovskyi** [eclipse-sirius/sirius-components#474]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
> Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

### Screenshots

![Screenshot 2021-06-03 at 21 40 50](https://user-images.githubusercontent.com/64734/120702521-7883e800-c4b4-11eb-8639-e2fd925ede33.png)

![S38333EETT A](https://user-images.githubusercontent.com/64734/117003542-4466ad00-ace5-11eb-97d2-edde84e1285d.jpg)

### Steps to reproduce

1. Add to `SampleSiriusConfiguration` from https://github.com/eclipse-sirius/sirius-web a Sirius model configuration for [ToolChainModel.odesign](https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign). It will reference [vocabulary.ecore](https://github.com/eclipse/lyo.designer/blob/master/org.eclipse.lyo.oslc4j.adaptormodel/model/vocabulary.ecore).
2. Add a bean method for providing an `AdaptorFactory` to be an instance of `VocabularyItemProviderAdapterFactory` ([package](https://github.com/eclipse/lyo.designer/tree/master/org.eclipse.lyo.tools.vocabulary.model/src/vocabulary)).
3. Add a bean method for providing an `EPackage` to return `VocabularyPackage.eINSTANCE`.
4. Add a bean method to supply for LabelFeature and Editable switches.
5. Add a stereotype description to `StereotypeDescriptionRegistryConfigurer`.
6. Launch the sample web application.

### Expected behavior

When I try to add a new element to a model, the initial AQL expression for the element is evaluated correctly.

1. I add a new element to the model.
2. The element creation includes some actions that need to be evaluated using AQL. For example, setting the element name with `aql:'Class ' + container.classes->size()`.
3. The element name should evaluate to `"Class 3"` if there are already 2 elements in the model.

### Actual behavior

The element name is always evaluated to `"Class "`, the AQL is evaluated incorrectly. AQL expression that do not rely on the `vocabulary.ecore` ECore model seem to run fine.

---

We have investigated the AQLInterpreter and found that it rejects our Vocabulary EPackage as invalid. 
We tried two possible fixes:

1. Replace the workspace reference to the .ecore from the .odesign to a URI reference just like in the Flow model.
2. Replace the implementation config in the genmodel from `MinimalEObjectImpl` to the default one.

Neither change seems to help (nor both together).

Thank you in advance!

**Comment by berezovskyi** [comment]
@pcdavid, I apologise for not stating the problem clearly the first time. I updated the description. Could you please take another look at it?

**Comment by pcdavid** [comment]
Hi.

From what I see in the screenshot the first solution you mention (referencing the metamodel's nsURI from the odesign instead of a workspace path (which only makes sense in an Eclipse context) should work.
Maybe there is something specific in how you set up your projects and their dependencies. We never had this specific issue, but maybe by chance. Hopefully we will find the issue later today during the SiriusCon Clinic.

Note that the implementation class (`MinimalEObjectImpl` or other) should not have any impact here. This only applies to the actual instances of your metamodel, not to the `EPackage(Impl)` itself which is at issue here.

**Comment by berezovskyi** [comment]
Thank you for your help today, @pcdavid!

We can close this issue, the resolution is to:

1. Use a URI to reference an Ecore model instead of a workplace reference.
2. Make sure the URI reference terminates with the characters `#/` (no changes are necessary to the Ecore model Ns URI)

Also, as you have indicated, the right place to verify the fix was correct is after `resource.load()` in the [`ODesignReader`](https://github.com/eclipse-sirius/sirius-components/blob/v0.2.19/backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/representations/ODesignReader.java#L96) (the metamodel shall contain real instances of the EPackages and not EMF proxies):

<img width="1245" alt="Screenshot 2021-06-16 at 17 19 20" src="https://user-images.githubusercontent.com/64734/122250010-99dbcf80-cec9-11eb-8a23-18b32efbe5ea.png">

cc @jadelkhoury

**Comment by pcdavid** [comment]
Great news!
Thanks for confirming this was indeed the issue.

**Comment by jadelkhoury** [comment]
🍾
