### ISSUE TITLE
Improve the default values of the domain and view

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#557]
### Problem

When we create new elements in the Domain or View DSL, most of the fields are empty. This helps creating invalid definitions.

### Solution

Populate some of the properties with relevant default values.

#### Domain DSL

- [ ] All elements should be created with an initial non-null name.

#### View DSL

- [ ] All attributes should be created with valid/non-empty values.
  - [ ] Styles currently have `rgb(0, 0, 0)` as both color and border color (which is used for text), meaning the default is an unreadble "black on black".
  - [ ] Conditions on conditional styles should be initialized with `aql:false`. Technically this does not change anything (an empty expression is treated as a false one), but it makes things more explicit.
- [ ] Object creation from the explorer delegates to EMF Edit's `collectNewChildDescriptors`, so be should customize this to automatically create required children elements. In particular both node and edge descriptions should be created with a default style already set.

### Test

* [ ] Automated developer tests merged and pass (with reasonable code coverage)
* [ ] Automated End-to-End tests  merged and pass (Cypress)
* [ ] Feature/bug fix manually tested/validated by at least one person not involved in the implementation
* [ ] Collaborative tests passed by hand
* [ ] Exploratory test passed by MEB
* [ ] Business acceptance test passed by MEB

### Doc
* [ ] Internal Doc updated
* [ ] External Doc updated
* [ ] Validation Doc updated

### Next
* [ ] Any left-over tasks added to the issues on Github

**Comment by pcdavid** [comment]
### Domain DSL

* All elements should be created with an initial non-null name.

### View DSL

* Styles currently have `rgb(0, 0, 0)` as both color and border color (which is used for text), meaning the default is an unreadble "black on black".
* Object creation from the explorer delegates to EMF Edit's `collectNewChildDescriptors`, so be should customize this to automatically create required children elements. In particular both node and edge descriptions should be created with a default style already set.
