### ISSUE TITLE
The "Download" menu entry is underlined

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#610]
In the model explorer, the "Download" context menu item for documents has an inconsistent style, with a visible blue underline (as it is implemented by a `<a/>` element underneath):
![2021-07-05_09-11](https://user-images.githubusercontent.com/10608/124432108-83f75700-dd71-11eb-944c-9dc79d0321e2.png)

**Comment by sbegaudeau** [comment]
The fix merged is based on a global CSS rule which will create more problem than anything.
