### ISSUE TITLE
Add support for external java actions

### ISSUE THREAD

**Issue by Camork** [eclipse-sirius/sirius-components#613]
Reference to the [document](https://www.eclipse.org/sirius/doc/specifier/general/Model_Operations.html#external_java_action), we need to support this feature in sirius web.

* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

The external java action declaration in OD file should work.

### Cuttings backs

...

### Potential side effects

no

### Describe alternatives you've considered

no

**Comment by sbegaudeau** [comment]
We should probably take over this PR by ourselves since the comments I made on the PR have not all been taken into account.

**Comment by sbegaudeau** [comment]
Merged in master
