### ISSUE TITLE
Improve diagram ergonomics

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#616]
This issue aggregates several bug fixes and improvements that we would like to fix for version 0.4.0 to improve the look & feel of diagrams in general.

Here is the list of the closed diagram related issues for the 0.4.0 release:

- [Closed diagram issues for v0.4.0](https://github.com/eclipse-sirius/sirius-components/issues?q=is%3Aissue+label%3A%22area%3A+diagram%22+project%3Aeclipse-sirius%2Fsirius-components%2F2+is%3Aclosed)

Here is the list of the remaining issues on this topic:

- [Open diagram issues](https://github.com/eclipse-sirius/sirius-components/issues?q=is%3Aissue+label%3A%22area%3A+diagram%22+is%3Aopen)

**Comment by sbegaudeau** [comment]
The scope of the 0.4.0 is now closed
