### ISSUE TITLE
The default value for the edge description color makes it barely visible

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-components#646]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- my computer: Windows
- Cloud

### Screenshots

![image](https://user-images.githubusercontent.com/7371042/126636957-45283630-301f-4e2d-8ecf-e6ee94f725f6.png)

### Steps to reproduce

1. In a "Studio" project:
2. Define a view on a domain
3. Define an Edge description. Keep default color value
4. In an "Instance" project:
5. Create a diagram and create an edge based on the Edge description

### Expected behavior

The edge should be visible with a human eye.

### Actual behavior

The edge is barely visible.

**Comment by pcdavid** [comment]
I don't reproduce. For me, both on staging and locally, a newly created EdgeDescription has a style with color `#002639`:

![2021-07-23_11-04_1](https://user-images.githubusercontent.com/10608/126760667-bb8294c3-bc99-4683-a995-093f8533a5e4.png)

Which looks like this:

![2021-07-23_11-04](https://user-images.githubusercontent.com/10608/126760694-02c53086-9113-4838-9aaa-702877e0657b.png)

There is however an issue with the default value for the 'Target Arrow Style', which should be _Input Arrow_ (as on the screenshot above) insted of _Output Arrow_ as it is now. I'll prepare a fix for that.

**Comment by pcdavid** [comment]
Ah, I see. The bug is indeed present, but for the default value on *conditional edge styles*.
