### ISSUE TITLE
Add additional variables to execute tools

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#690]
### Problem

In order to support some additional use cases, we may need to provide additional variables to apply some tools. We also need to document the variables available for the various functions.

### Solution

We will create a small document listing the variables available for the various functions starting with the diagram part and we will figure out which variable are missing (and why) and add them where it is necessary.

This document will serve as the contract between Sirius Components and those who which to reuse it.

### Test
* [ ] Automated developer tests merged and pass (with reasonable code coverage)
* [ ] Automated End-to-End tests  merged and pass (Cypress)
* [ ] Feature/bug fix manually tested/validated by at least one person not involved in the implementation
* [ ] Collaborative tests passed by hand
* [ ] Exploratory test passed by MEB
* [ ] Business acceptance test passed by MEB

### Doc
* [ ] Internal Doc updated
* [ ] External Doc updated
* [ ] Validation Doc updated

### UX/UI
* [ ] Zeroheight updated
* [ ] Storybook updated

### Next
* [ ] Any left-over tasks in the Github issues

**Comment by hmarchadour** [comment]
I propose to add 
CreateNodeTool.**SELECTED_NODE** in the variable manager that will contains the selected node for deletion/creation/drop use-cases. It will be useful for unsynchronized tool implementations.
We will set this variable in : 
* the InvokeNodeToolOnDiagramEventHandler#execute
* the DeleteFromDiagramEventHandler#invokeDeleteNodeTool
* a future InvokeDropToolOnDiagramEventHandler #132

**Comment by hmarchadour** [comment]
Use **CreateNodeTool**.SELECTED_NODE is litigious for DeleteFromDiagramEventHandler...
Perhaps on Node instead of  CreateNodeTool.
