### ISSUE TITLE
[View] The generic edge tool should not be added when on custom Edge is provided

### ISSUE THREAD

**Issue by adaussy** [eclipse-sirius/sirius-components#735]
* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** : 0.4.6 latest
* [ ] **I have specified my environment** : All

### Steps to reproduce

In a view model with a EdgeDescription provide an Edge tool.

### Expected behavior

Only the custom tool should be displayed in the instance modeler (like in NodeDescription)

### Actual behavior

Both tools are displayed and usable.

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse-sirius/sirius-components/pull/736.
