### ISSUE TITLE
Reconnecting edges

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-components#780]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Add a way to reconnect existing edges to match parity with Sirius Desktop.

![image](https://user-images.githubusercontent.com/889383/137632957-65884a28-d356-48f1-b4c0-9ee378aa0106.png)

It would be great if _Reconnect Edge_ tools were taken into account too.

### Cuttings backs

I don't know what this section means.

### Potential side effects

Not sure.

### Describe alternatives you've considered

Users can delete the edge and create a new one, or change source/target in the _Details_ pane. The former solution results in subpar UX, the latter does not leverage the UI and requires picking an element from a potentially long list.

**Comment by gcoutable** [comment]
ADR: https://github.com/eclipse-sirius/sirius-components/pull/1177
