### ISSUE TITLE
Fit to screen does not work after panel resize

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#786]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : latest
* [x] **I have specified my environment** : 
Cloud
### Screenshots
![image](https://user-images.githubusercontent.com/1185863/137734257-08b06c59-195c-4862-b787-3dc9d1ce32cd.png)

### Steps to reproduce
1. Open a diagram
2. Select the diagram's background
3. Select Fit to screen
-> The diagram fits all in the editor
4. Resize the Dateils view panel
5. Select the diagram's background
6. Select Fit to screen
-> The diagram does not fit in the editor

### Expected behavior

The size used to fit a diagram should be the size of the diagram editor after resizing the panels.

### Actual behavior

THe sisze used to compute the fit to screen seems to be the first one before the panel resize.

**Comment by pcdavid** [comment]
It seems to work fine now with React Flow diagrams. Feel free to reopen if I missed something.
[Capture vidéo du 2023-12-08 10-29-02.webm](https://github.com/eclipse-sirius/sirius-web/assets/10608/90e750bd-2b2a-48da-874c-c5750d7f6e12)
