### ISSUE TITLE
Edges connected to moved elements are reset to a single segment

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#801]
This is a followup to https://github.com/eclipse-sirius/sirius-components/issues/550.
It used to be that moving any element on a diagram (in manual layout mode) would reset all (or at least most) edge to single segments with no bendpoints, even if the edge was between elements which were not moved at all.
The fix for https://github.com/eclipse-sirius/sirius-components/issues/550 improved the situation, be we still reset the edges connected to a moved element to single segments, losing any previous routing information.

**Comment by gcoutable** [comment]
It will be fixed when https://github.com/eclipse-sirius/sirius-components/issues/997 will be merged
