### ISSUE TITLE
Support custom style

### ISSUE THREAD

**Issue by Camork** [eclipse-sirius/sirius-components#823]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

Node  style can be customized by giving a style ID.

### Cuttings backs

...

### Potential side effects

no

### Describe alternatives you've considered

The default style can't meet the demand, It would be flexible to allow define the custom style ID in VSM and provide implement in frontend.

**Comment by sbegaudeau** [comment]
The style needs to be handled by the backend in order to compute the layout of the diagram. So we can add new styles but we can't delegate everything to the frontend to do anything it want. Today, it is possible for someone to compute the SVG of a diagram fully server side since we have all the information for that (we don't provide that right now but we have everything to do it, it's not very complicated).

**Comment by Camork** [comment]
I think it's OK to compute the layout in server , but what if a figure contains the dynamic content will be updated by a model's property?
For example:
A model has a color property , the figure's color will follow the property's change.
A model has a number property that will change the amount of the border nodes , and the figure will display this number to indicate that how many border nodes the current node have.

**Comment by sbegaudeau** [comment]
We already support computed styles. In our flow sample, the appearance of the data source is computed from their name (try Wifi or Radar). In a similar fashion, we have example where the size of the rectangle is computed from a property with the type integer.

**Comment by Camork** [comment]
What if I want to make the fan spin faster when I change the speed property in flow example? (May I need to regenerate the svg),  I can use the conditional style to handle the limited number of enum values,  but it can't handle a random value like speed value from 1 to 100000 etc.

**Comment by sbegaudeau** [comment]
Technically, you can create a style computed from some properties, for example using `NodeDescription#getStyleProvider()` you could say that the style is an `ImageNodeStyle` with the URL `fan.svg?speed=10` or `fan.svg?speed=10000` (this can be computed from the properties of the object). From that, when you will need to provide the fan image using a regular Spring Controller, you can create / customize it programmatically.

Sirius Components allows that but Sirius Web does not offer the way to do it. In Sirius Web, we would need to allow specifiers to provide an image for the requested path (regardless of how the image is retrieved / created) in the `ImageController`. Right now, Sirius Web will only look for the image in the class path (`new ClassPathResource(imagePath)`) so Sirius Web expects that the image is a static resource.

**Comment by Camork** [comment]
I think this maybe  be a good solution , thanks.
