### ISSUE TITLE
Switch to Sirius Desktop 6.6.0 when it is released

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#845]
We are [currently](https://github.com/eclipse-sirius/sirius-components/blob/master/backend/sirius-web-compatibility/pom.xml#L31) using Sirius Desktop version 6.5.1 for the compatibility layer.

[Sirius Desktop 6.6.0](https://projects.eclipse.org/projects/modeling.sirius/releases/6.6.0) should be released soon. I don't think the changes in that version should impact us (positively or negatively), but we should still plan the switch in order to stay current and consistent.

Note that version 7.0 of Sirius Desktop, which should be release in Q1 2022 will have more impacting changes.

**Comment by sbegaudeau** [comment]
Are there any dependency change in Sirius 6.6.0 that we need to deal with? New version of AQL, update in the range of Ecore used, additional dependency?

**Comment by pcdavid** [comment]
No dependency change at all between 6.5.1 and 6.6.0.

**Comment by pcdavid** [comment]
[Sirius Desktop 6.6.0](https://projects.eclipse.org/projects/modeling.sirius/releases/6.6.0) was officially released last friday.
