### ISSUE TITLE
ADR-36 has no status

### ISSUE THREAD

**Issue by nostneji** [eclipse-sirius/sirius-components#856]
### Expected behavior
According to ADR-0 every ADR should have section "Status".

### Actual behavior
ADR-36 in https://github.com/eclipse-sirius/sirius-components/blob/master/doc/adrs/036_adopt_a_more_structured_selection.adoc has no status defined.

Btw, perhaps it would be good to add a hint to the status of what milestone it was or should be realized.

**Comment by sbegaudeau** [comment]
Thanks for noticing, we will add a status to this ADR, the work on this topic has already been started and it will be integrated in the next iteration. Maybe as early as next week. See https://github.com/eclipse-sirius/sirius-components/pull/854

**Comment by sbegaudeau** [comment]
I'll close this issue since it will be fixed by the PR that I have referenced.
