### ISSUE TITLE
Review our dependencies and update if relevant

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#860]
We already have #841 for Spring Boot and #845 for Sirius Desktop, but we should also have a look at others, both on the frontend and backend, and upgrade if relevant.

**Comment by sbegaudeau** [comment]
### Backend

- Spring Boot 2.6.1
- GraphQL Java 17.3 https://github.com/graphql-java/graphql-java/releases/tag/v17.3
- Sirius RCP 6.6.0

### Frontend

<img width="773" alt="Capture d’écran 2021-12-03 à 10 40 22" src="https://user-images.githubusercontent.com/422587/144580780-2d522423-a131-457a-b661-f294eb28e82a.png">

**Comment by sbegaudeau** [comment]
We should probably consider if it's still relevant to embed GraphiQL and GraphQL Voyager. It creates bigger artifacts and we are bringing outdated version of both projects. There are also some alternatives.

**Comment by pcdavid** [comment]
Short video about upgrading to React Router 6.0 (which changed some APIs): https://www.youtube.com/watch?v=k2Zk5cbiZhg

**Comment by pcdavid** [comment]
[Spring Framework 5.3.14](https://spring.io/blog/2021/12/16/spring-framework-5-3-14-and-5-2-19-available-now) has been released, so a new Spring Boot version will probably follow soon (Spring Boot 2.6.1 uses Spring Framework 5.3.13).

**Comment by pcdavid** [comment]
For information, see also [Spring 6.0M1](https://spring.io/blog/2021/12/16/spring-framework-6-0-m1-released) and https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x for the future.

**Comment by sbegaudeau** [comment]
We will have to keep in mind that [Spring Framework 6 has a Java 17 baseline](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) contrary to Spring Framework 5.3.x which is still in Java 8 and Java 11 for its baseline so it will be a big jump for everybody.

**Comment by sbegaudeau** [comment]
Closing this issue since it has been merged on master
