### ISSUE TITLE
AQL is not interpreted correctly in style customizations for image `workspacePath`

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-components#865]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- other: 0.5.3
* [x] **I have specified my environment** : 
- Ubuntu 20.04 LTS

### Screenshots

Some of my style customizations in the odesign file use AQL. An example style customization:

![image](https://user-images.githubusercontent.com/889383/144719096-24eef6b4-472f-4c76-b76c-48ac6098c54c.png)

`getDataPinIconPath` is defined in my metamodel's `Services`.

It works well in Sirius Desktop:

![image](https://user-images.githubusercontent.com/889383/144719112-3b3c1a25-006e-46b7-9113-5b22c0daa577.png)

But there are no images shown in Sirius Web:

![image](https://user-images.githubusercontent.com/889383/144719070-1bc0b763-12a1-4404-b0e1-cc1bd7805e74.png)

The image path that Sirius Web wants to load is:

```
http://localhost:3000/api/images/eu.balticlsc.model.CAL.edit/icons/computed-data-pin/'%20+%20self.declared.getDataPinIconPath()
```

whereas it should be:

```
http://localhost:3000/api/images/eu.balticlsc.model.CAL.edit/icons/computed-data-pin/single-data-single-token.png
```

### Steps to reproduce

1. Add a metamodel style customization using AQL for the `workspacePath` of an image of a node

### Expected behavior

The image is loaded correctly using the same logic as in Sirius Desktop.

### Actual behavior

The image is not loaded due to a malformed URL.

**Comment by pcdavid** [comment]
It looks like:

https://github.com/eclipse-sirius/sirius-components/blob/41554cd0ebe94107ad218c4f33272731a6b2bf48/backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/WorkspaceImageDescriptionConverter.java#L53

**Comment by pcdavid** [comment]
@Gelio can you try your use case with
```java
        // @formatter:off
        String workspacePath = this.eAttributeCustomizationProvider.getEAttributeCustomization(this.workspaceImageDescription, WORKSPACE_PATH)
                .map(EAttributeCustomization::getValue)
                .flatMap(expression -> this.interpreter.evaluateExpression(this.variableManager.getVariables(), expression).asString())
                .orElse(this.workspaceImageDescription.getWorkspacePath());
        // @formatter:on
```
in `org.eclipse.sirius.web.compat.diagrams.WorkspaceImageDescriptionConverter.convert()`?

**Comment by Gelio** [comment]
@pcdavid Sorry, I don't have my own fork of sirius-components set up to be consumed in Sirius Web. I am only using the public version of sirius-components. I don't have the bandwidth right now to set up a fork to test it out

**Comment by pcdavid** [comment]
@Gelio the fix mentioned in my earlier comment should now be available starting from version 2021.12.6. Could you confirm if it fixes the issue for you?

**Comment by Gelio** [comment]
There were some pretty heavy changes since the last time I updated my fork of sirius-web. I have just spent 1.5h trying to apply those 20 commits, but I probably messed something up, as I missed the changes from some of the commits. I don't have the bandwidth right now to redo the process.

**Comment by Gelio** [comment]
I had a bit more time today and applied the patch correctly this time.

I confirm that the problem is solved:

![image](https://user-images.githubusercontent.com/889383/147644830-9dcde4d5-1194-4682-b4cd-323d4a58d61b.png)

Thanks!

**Comment by pcdavid** [comment]
Good news, thanks for your feedback!
