### ISSUE TITLE
Allow to make specific changes before and after the layout

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-components#896]
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

As it is possible in SiriusDesktop (https://bugs.eclipse.org/bugs/show_bug.cgi?id=547598) SiriusComponents could allow to make 
specific changes before and after the layout.

### Potential side effects

Default implementation of beforeLayout and afterLayout won't do anything so no side effects.

**Comment by sbegaudeau** [comment]
Merged in master
