### ISSUE TITLE
All diagram elements should be visible in the canvas when a diagram is open

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-components#925]
### Screenshots

![image](https://user-images.githubusercontent.com/7371042/148551171-ecc9ec8c-c567-4bdf-878b-f68a96203fe8.png)

### Steps to reproduce

Open any diagram.

### Expected behavior

All diagram elements should be displayed in the canvas bounds, even those with negative coordinates.

### Actual behavior

It may happen that some diagram elements have negative coordinates. These elements are not visible because they are outside the canvas bounds.

**Comment by pcdavid** [comment]
Since this change, when I have a diagram visible and resize the browser window the viewport is **very slowly** adjusted to fit the new size. Like, almost 10s where I can not interact with the diagram at all until the animation is finished.

**Comment by sbegaudeau** [comment]
I'll re-close this issue since the feature has been done and contributed but I have created [another issue](https://github.com/eclipse-sirius/sirius-components/issues/957) for the potential performance issue.
